set(
  SUCRE_SNORT_MAINLINE_INCLUDE_DIRS
  "${CMAKE_SOURCE_DIR}/src"
  "${CMAKE_SOURCE_DIR}/src/main"
  "${CMAKE_SOURCE_DIR}/src/control/vnext"
  "${CMAKE_SOURCE_DIR}/src/platform/android"
  "${CMAKE_SOURCE_DIR}/src/datapath/nfqueue"
  "${CMAKE_SOURCE_DIR}/src/core/packet"
  "${CMAKE_SOURCE_DIR}/src/core/policy"
  "${CMAKE_SOURCE_DIR}/src/core/metrics"
  "${CMAKE_SOURCE_DIR}/src/app"
  "${CMAKE_SOURCE_DIR}/src/config"
)

set(
  SUCRE_SNORT_DAEMON_SOURCES
  "${CMAKE_SOURCE_DIR}/src/main/daemon_main.cpp"
  "${CMAKE_SOURCE_DIR}/src/main/DaemonRuntime.cpp"
  "${CMAKE_SOURCE_DIR}/src/control/vnext/ControlServer.cpp"
  "${CMAKE_SOURCE_DIR}/src/control/vnext/ControlVNextCodec.cpp"
  "${CMAKE_SOURCE_DIR}/src/datapath/nfqueue/NfqueueHookInstaller.cpp"
  "${CMAKE_SOURCE_DIR}/src/datapath/nfqueue/NfqueueHookPlan.cpp"
  "${CMAKE_SOURCE_DIR}/src/datapath/nfqueue/NfqueuePassThrough.cpp"
  "${CMAKE_SOURCE_DIR}/src/datapath/nfqueue/NfqueuePassThroughRuntime.cpp"
)
